### ISSUE TITLE
Avoid scrolling page on tab switch

### ISSUE THREAD

**Issue by akhmerov** [pradyunsg/sphinx-inline-tabs#1]
Right now the tabs are vertically centered on click.

**Comment by pradyunsg** [comment]
AH. interesting!

Browser? OS?

**Comment by akhmerov** [comment]
I was too hasty, the vertical scrolling behavior seems to vary.

On ubuntu+chrome the first tab set [here](https://sphinx-inline-tabs.readthedocs.io/en/latest/usage.html#basics) centers the page, on ubuntu+firefox it is positioned at the top of the screen. The lower sets of tabs also center on chrome, and scroll to some weird intermediate location on FF.

Python/C++ or windows/unix tab sets on the same page don't scroll in neither browser.

**Comment by pradyunsg** [comment]
Hmmm! Can reproduce on Blink-based browsers (Chrome family). Can't reproduce on FireFox, but I think I have what I need.

**Comment by pradyunsg** [comment]
cf59521cd3967b0a7cb14559228d41afbb87f130 should fix this -- could you check the latest documentation (it'll build in a few minutes) and confirm whether it is indeed fixed?

**Comment by akhmerov** [comment]
I confirm that vertical repositioning doesn't happen. However

![image](https://user-images.githubusercontent.com/2069677/96053520-f345b780-0e7f-11eb-9dda-1abd582cff10.png)

![image](https://user-images.githubusercontent.com/2069677/96053537-fb9df280-0e7f-11eb-95cc-a59d775a413f.png)

**Comment by pradyunsg** [comment]
HUH.

**Comment by pradyunsg** [comment]
I'll come back to this tomorrow -- browsers are weird.

**Comment by akhmerov** [comment]
Everything seems to work now!

**Comment by pradyunsg** [comment]
Was fixed by https://github.com/pradyunsg/sphinx-inline-tabs/commit/d17680c111c472f9929ce6791266e483d24647a2. :)
