### ISSUE TITLE
Large height differences between tab content causes problems with synchronisation

### ISSUE THREAD

**Issue by evildmp** [pradyunsg/sphinx-inline-tabs#11]
When you have a large height difference between the content of one set of tabs, and then switch tabs further down the page, the height difference above causes content to move around - sometimes so much that what you were looking at disappears from the page.

In the example below, when selecting from the second set of tabs, they move away from the position they were in.

Example:

```
..  tab:: Tall

    many
    lines
    of
    content
    many
    lines
    of
    content
    many
    lines
    of
    content
    many
    lines
    of
    content
    many
    lines
    of
    content

..  tab:: Short

    one line

Back to untabbed content, briefly.

..  tab:: Tall

    more stuff

..  tab:: Short

    more stuff

**Comment by pradyunsg** [comment]
That's inherent given how things work. What's the concern here?

**Comment by pradyunsg** [comment]
Closing due to lack of a response.
