### ISSUE TITLE
Using `:math:` directives in the beginning of tab titles renders raw html 

### ISSUE THREAD

**Issue by stonecharioteer** [pradyunsg/sphinx-inline-tabs#13]
Found an interesting bug.

```
.. tab:: :math:`O(n)`
    
    hello world
````

Will render `<math>O(n)</math>`, while using the directive somewhere in the *middle* of a tab's title seems to be fine.

Here are screenshots of the problem

![Screenshot from 2021-03-26 16-49-20](https://user-images.githubusercontent.com/11478411/112624224-5a19c480-8e53-11eb-8f2e-2f0250ee81f5.png)

Naturally, I'm using Furo.

[I've made a branch to show the error.](https://github.com/stonecharioteer/notes/blob/bug/sphinx-inline-tabs/source/interview-prep/leetcode/0001-two-sum/index.rst#L13) (`make livehtml` should work for you once you've set up the requirements.)

Later additions:
Also, I've got more interesting variations of this bug.

Play around with the titles, I've tried using `:term:` with a glossary file, and this just *fails* at the build stage. Doesn't seem to be a 
sphinx bug, but I am not sure.
Log here: [sphinx-err-b9355wxr.log](https://github.com/pradyunsg/sphinx-inline-tabs/files/6211582/sphinx-err-b9355wxr.log)

Let me know how I can be of help.

**Comment by pradyunsg** [comment]
Fixed in 1e9daf3f1086843d42d2eb40db9fff3960453177. I'll cut a release later today! :)

**Comment by pradyunsg** [comment]
https://pypi.org/project/sphinx-inline-tabs/2021.4.11b8/ -- actually, now. :)
