### ISSUE TITLE
Allow to disable synchronization 

### ISSUE THREAD

**Issue by janluke** [pradyunsg/sphinx-inline-tabs#20]
Synchronization may be a good default but it shouldn't be enforced. There's a common scenario for tabs where synchronization is not desirable: the "input / output" scenario. I think it is as common as the "multiple languages" scenario, if not more common.

I'm using sphinx-panels at the moment but it'd be nice to have this feature in this nice extension.

Thanks for your work!

**Comment by pradyunsg** [comment]
Closing as a duplicate of #18, since it's the same usecase.
