### ISSUE TITLE
toggling tabs cause page to jump

### ISSUE THREAD

**Issue by havok2063** [pradyunsg/sphinx-inline-tabs#21]
I have a single page with several sets of two tabs, e.g each tab contains a code-block for a CLI command and equivalent code in Python.  For the first tab set on the page, toggling the tabs back and forth is smooth.  However, for all subsequent tab sets on the page, when I toggle between the two tabs, it causes the page to jump erratically back and forth, as if it was jumping to an internal anchor on the page.  This behavior isn't present in your usage docs, so maybe it's an issue with how I'm creating the tabs or another bug? 

Each tab set is pretty much the same , e.g.
```
.. tab:: CLI

    .. code-block:: console

        $ command-line code

.. tab:: Python

    .. code-block:: python

        python code

```

**Comment by pradyunsg** [comment]
Is the content in the two blocks the same height? If not, that might be the culprit here.

Sadly, there’s no way to solve this in this extension; so my recommendation in these cases is to tweak your content to be approximately equal height.

**Comment by havok2063** [comment]
Hmm.  No they aren't the same height.   For all the tab sets, one tab has 3 lines in it, the other tab has about 10 lines in it.   I wonder why it's not an issue for the first tab, but only for the rest.  In my current example, the page contains two tab sets.  The first tab set toggles smoothly, the second set toggles erratically.  I tried changing the second set so each tab has the same number of lines.  I still get the jumpy behavior.   But when I also change the first tab set each tab also has 3 lines, then both sets toggle smoothly.   So it seems like the content in prior tabs on a page can affect how later tabs behave.   I'll see if I can play around with it.

**Comment by havok2063** [comment]
I realized it's partially due to the fact that all tabs are synced with each other, so the page isn't necessarily jumping around, but the added text changes the overall length of the page.  But I have found that sometimes the jump can be quite large, like half the page, which is unfortunate but manageable.  

I wonder if it's possible to create hidden internal anchor points on each tab, so as you toggle between tabs, it uses that anchor to "lock" to that tab even as text length or height changes.

**Comment by pradyunsg** [comment]
Closing this since I don't think there's anything that I can do for this *right now*.

> I wonder if it's possible to create hidden internal anchor points on each tab, so as you toggle between tabs, it uses that anchor to "lock" to that tab even as text length or height changes.

Maybe, I'll have to try out how to make that works -- it makes sense to bundle this into #27. :)
