### ISSUE TITLE
Make it possible to change the "default" selected tab

### ISSUE THREAD

**Issue by ma-sadeghi** [pradyunsg/sphinx-inline-tabs#23]
Is there a way to choose the default selected tab? Currently, the first tab is selected by default.

**Comment by feorlen** [comment]
Related to @ma-sadeghi's comment, is there a way to link to a specific tab? I'd like to share a url for specific content in one tab of several. Thanks!

**Comment by pradyunsg** [comment]
> Is there a way to choose the default selected tab?

No.

> is there a way to link to a specific tab?

No. Filed #27 for it.
