### ISSUE TITLE
Explain the differences from sphinx-tabs in the README

### ISSUE THREAD

**Issue by SnirBroshi** [pradyunsg/sphinx-inline-tabs#25]
[sphinx-tabs](https://github.com/executablebooks/sphinx-tabs) was the way to create tabs in Sphinx before this extension was made, so I assume there are good reasons for creating a competing extension.

The README lists under "Features" some benefits of this extension such as small footprint, but can you add an explicit comparison with sphinx-tabs?

I think it will help people (like me) choose. Thanks!

**Comment by pradyunsg** [comment]
> The README lists under "Features" some benefits of this extension such as small footprint, but can you add an explicit comparison with sphinx-tabs?

I'm not sure this is necessary?

The list of features is literally the list of things that are different from sphinx-tabs -- a cleaner design, that's customisable, works without JS and has synchronisation. All of these are things that sphinx-tabs did not, when this extension was created.

**Comment by pradyunsg** [comment]
Plus, having an A/B comparision puts the onus on me to keep up with how sphinx-tabs evolves, to avoid misrepresenting that project. I don't want to have that additional work, TBH.

**Comment by pradyunsg** [comment]
Closing this out since I don't think I wanna try to keep up with changes that might happen in sphinx-tabs.
