### ISSUE TITLE
Declare parallel reading capabilities to remove Sphinx warnings

### ISSUE THREAD

**Issue by rixx** [pradyunsg/sphinx-inline-tabs#26]
Using sphinx-inline-tabs in a project gave me very loud Sphinx warnings – nothing important, but would be nice to get rid of eventually:

```
WARNING: the sphinx_inline_tabs extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

**Comment by kovidgoyal** [comment]
Here's how you can suppress this warning and enable parallel reads in your conf file's setup(app) function:

```py
    inline_tabs = app.extensions['sphinx_inline_tabs']
    inline_tabs.parallel_read_safe = inline_tabs.parallel_write_safe = True
```

**Comment by pradyunsg** [comment]
What version are you on? This has been declared for 9 months now.

https://github.com/pradyunsg/sphinx-inline-tabs/blame/cb11b9853969ee535660a4ef370ee8910bec3b07/src/sphinx_inline_tabs/__init__.py

**Comment by kovidgoyal** [comment]
2020.10.19.beta4-5

which is current in AUR. https://archlinux.org/packages/community/any/python-sphinx-inline-tabs/

**Comment by pradyunsg** [comment]
Yea, take that up with the Arch folks.
