### ISSUE TITLE
Allow use on Python 3.7

### ISSUE THREAD

**Issue by kdeldycke** [pradyunsg/sphinx-inline-tabs#28]
I'd love to switch from [`sphinx_tabs`](https://github.com/executablebooks/sphinx-tabs) to `sphinx-inline-tabs` but the hard requirement on Python >= 3.8 make it impossible to do so: my project works with Python >= 3.7, which is still getting security fixes until 2023-06-27.

So in the same spirit as #24, is there any possibility to have Python requirement relaxed to 3.7 as a minimum? 🙂

**Comment by pradyunsg** [comment]
Why do you need to generate the docs using Python 3.7?

**Comment by kdeldycke** [comment]
> Why do you need to generate the docs using Python 3.7?

True. I don't need to generate the docs in Python 3.7.

But my all my Sphinx dependencies for doc building are set in my `pyproject.toml`, which also specify the minimal Python version to 3.7: https://github.com/kdeldycke/meta-package-manager/blob/main/pyproject.toml#L92 . Hence the conflict.

This is really practical as I can propose to the developer a way to [build docs locally](https://kdeldycke.github.io/meta-package-manager/development.html#documentation) and test them, as straightforward as:
```shell
$ poetry install
$ poetry run sphinx-build -b html ./docs ./docs/html
```

Also, having all doc-related dependencies in `pyproject.toml` allow me to:
* Let [dependabot manage and notify me](https://github.com/kdeldycke/meta-package-manager/blob/2a170359269b27ebe2413089c47d0cc913e11b26/.github/dependabot.yaml#L7-L14) of new releases
* Simplify my [doc building workflow](https://github.com/kdeldycke/meta-package-manager/blob/2a170359269b27ebe2413089c47d0cc913e11b26/.github/workflows/docs.yaml#L53-L62) as I need to locally install my project for [`sphinx-click`](https://github.com/click-contrib/sphinx-click) extension to generate the [CLI documentation](https://kdeldycke.github.io/meta-package-manager/cli-help.html).

**Comment by kdeldycke** [comment]
Since I created this bug, I moved to [`sphinx-design`](https://github.com/executablebooks/sphinx-design) to render tabs, so I don't need [`sphinx-inline-tabs`](https://github.com/pradyunsg/sphinx-inline-tabs) anymore. Let's close this issue to keep the backlog lean.
