### ISSUE TITLE
Multiple sets with same name will change all sets

### ISSUE THREAD

**Issue by tony** [pradyunsg/sphinx-inline-tabs#29]
@pradyunsg Thank you for this package! Amazing!

<details>

<summary>tabs.js</summary>

https://github.com/pradyunsg/sphinx-inline-tabs/blob/b37a295f63162fabeffe088c0ba622f63e2ef8c2/src/sphinx_inline_tabs/static/tabs.js#L1-L21

</details>

<details>

<summary>example video</summary>

https://user-images.githubusercontent.com/26336/158036223-26276022-82fd-44f3-81b2-78bff9d1fbcb.mp4

</details>

In https://tmuxp.git-pull.com/examples.html ([file](https://github.com/tmux-python/tmuxp/blob/05486cc/docs/examples.md?plain=1)) I have multiple sets of [YAML] [JSON] tabs: 

![image](https://user-images.githubusercontent.com/26336/158035900-c8ec224e-93a4-4d17-8f60-fc8bd46939cb.png)

If you scroll to any of the sections, such as [Set tmux options](https://tmuxp.git-pull.com/examples.html#set-tmux-options), the page will jump because all the sets are switched based on the text

I will try to find a way to experiment locally, but using the `id`'s already provided (`id="tab-set--1-input--1"`) as a lookup table rather than text labels would be extremely effective.

**Comment by pradyunsg** [comment]
👋🏽 Hi @tony!

This is an explicitly intended feature. From the README:

> Synchronisation: Tabs with the same label all switch with a single click.

See #18 for discussion the behavior you're likely requesting here.

**Comment by tony** [comment]
@pradyunsg Thank you! 

P.S. the workaround at https://github.com/pradyunsg/sphinx-inline-tabs/issues/18#issuecomment-1039284736 by @kalekundert seems to do the trick.
