### ISSUE TITLE
Support for copy-button in code tabs

### ISSUE THREAD

**Issue by ralhei** [pradyunsg/sphinx-inline-tabs#32]
We are using the 'sphinx-copybutton' extension in our documentation which enables the reader to click on the code block and gets code (minus configured shell prompts) copied to the clipboard. 

Would it be possible to enable sphinx-inline-tabs to work with this (or a similar) copybutton extension? This would be an excellent combination.

**Comment by Nicoretti** [comment]
@ralhei
I think this issue can be closed.
If you add and enable the [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) extension, it works just fine if you are using it together with the `..code block::` or `.. literalinclude::` directives within the tabs (see also [my comment](https://github.com/pradyunsg/sphinx-inline-tabs/issues/31#issuecomment-1332064017) in #31).
