### ISSUE TITLE
PR for tabulated formats in rst/md

### ISSUE THREAD

**Issue by zerothi** [pradyunsg/sphinx-inline-tabs#36]
Hi, would it make sense to have the documentation show different tabs for rst/md formatting issues?

I at least managed to get the `rst` tabs to work with codes, but it seems (from the *md) files that you didn't get this to work? Or?

**Comment by pradyunsg** [comment]
Are you looking for something like https://github.com/pradyunsg/furo/blob/834e951f5567fc4b0aa3564d33c0f0011d459263/docs/reference/tabs.md?plain=1#L13-L19 ?

**Comment by zerothi** [comment]
Yes, I believe this is an outdated issue, sorry for the blurp!
