### ISSUE TITLE
Using this extension breaks `sphinx-build -b xml`

### ISSUE THREAD

**Issue by simonw** [pradyunsg/sphinx-inline-tabs#38]
With this extension installed and configured I started seeing this error:
```
% sphinx-build -b xml . _build
Running Sphinx v6.1.3
building [mo]: targets for 0 po files that are out of date
writing output... 
building [xml]: targets for 28 source files that are out of date
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] writing_plugins                                                                                                                          
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  3%] authentication                                                                                                                            
Exception occurred:
  File "/Users/simon/.local/share/virtualenvs/datasette-AWNrQs95/lib/python3.10/site-packages/docutils/nodes.py", line 2028, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'docutils.writers.docutils_xml.XMLTranslator'> visiting unknown node type: TabContainer
The full traceback has been saved in /var/folders/x6/31xf1vxj0nn9mxqq8z0mmcfw0000gn/T/sphinx-err-1wkxmkji.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
Key error message in there:

> visiting unknown node type: TabContainer

I tracked it down to this code in `docutils/docutils` here: https://github.com/docutils/docutils/blob/3b53ded52bc439d8068b6ecb20ea0a761247e479/docutils/docutils/nodes.py#L2021-L2031

**Comment by simonw** [comment]
I found a workaround for this - basically I disable the extension just for the purposes of running that `-b xml` command. I detailed that workaround here:
- https://github.com/simonw/datasette/issues/1153#issuecomment-1627450852

I made some notes on investigating this issue with `pdb` here:
- https://github.com/simonw/datasette/issues/1153#issuecomment-1627448542

It would be nice if this wasn't an issue, but it's not a blocker for me since I have a reasonable workaround (linking that here in case anyone else sees the same error and searches for it).

**Comment by pradyunsg** [comment]
Hmm... What behaviour would you expect when building XML with this extension?

**Comment by simonw** [comment]
Best I can think of would be the equivalent of not having the tabs there at all - so it outputs the XML equivalent of the different tab blocks following each other.

My use case for the XML is building a searchable index of my documentation using https://github.com/simonw/sphinx-to-sqlite

**Comment by pradyunsg** [comment]
Resolved with https://github.com/pradyunsg/sphinx-inline-tabs/commit/1b5263d33b84b596fd9c82e762a3b1ff3b88409c.

I've going ahead and kept the content inline instead of omitting the tabbed content entirely.
