### ISSUE TITLE
There's no link to the documentation from the PyPI page

### ISSUE THREAD

**Issue by nedbat** [pradyunsg/sphinx-inline-tabs#41]
I would make a PR to add one, but I'm not familiar with Flit...

**Comment by pradyunsg** [comment]
Whoops! In case you wanna file a PR and get to this before me (later this week), here's an example:

https://github.com/pypa/flit/blob/a2594827306415db39a984124058339f5085a95c/pyproject.toml#L42

**Comment by hugovk** [comment]
Fixed by https://github.com/pradyunsg/sphinx-inline-tabs/pull/42.
