### ISSUE TITLE
Are there any tests?

### ISSUE THREAD

**Issue by hroncok** [pradyunsg/sphinx-inline-tabs#6]
Hello. I see the nox configuration and the test extra definition here, but there seem to be no tests at all. Is that the case?

(I am packaging this into Fedora, for pip, and this got me confused a bit.)

**Comment by pradyunsg** [comment]
Not yet, no.

I just that noxfile template in a bunch of my projects, hence the redundancy. I'll explore adding tests, but that's pretty low priority as you might imagine. :)

**Comment by hroncok** [comment]
Thanks
