### ISSUE TITLE
RFE: PEP 440 compatible git tags

### ISSUE THREAD

**Issue by hroncok** [pradyunsg/sphinx-inline-tabs#7]
Hello. it seems this packages has version defined as `2020.10.19.beta4` whilst flit happily converts that to `2020.10.19b4` when packaging the sdist and wheel. o the git tag is not equal to the version on PyPI.

Would you please consider using a [PEP 440](https://www.python.org/dev/peps/pep-0440/) compatible version tag for the next beta? Thanks.

**Comment by pradyunsg** [comment]
Yup. Same for Furo, I guess.

**Comment by hroncok** [comment]
Thanks

**Comment by pradyunsg** [comment]
ACTUALLY. [PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-release-spelling) does permit spelling as `beta4`.

I imagine the difference in the git tag and upstream release files might be the underlying issue for you?

**Comment by hroncok** [comment]
Oh, mea culpa.

> I imagine the difference in the git tag and upstream release files might be the underlying issue for you?

Yes, indeed. It's not a big issue, just an inconvenience.
