### ISSUE TITLE
Doesn't support tables

### ISSUE THREAD

**Issue by ziawaqqas** [pradyunsg/sphinx-inline-tabs#8]
Do the inline tabs donot support tables or am I missing something?

**Comment by pradyunsg** [comment]
Could you provide more context on what you mean here? Having a table seems to work fine for me!


https://user-images.githubusercontent.com/3275593/104123488-65c11900-5343-11eb-9274-260024085cb3.mov

**Comment by ziawaqqas** [comment]
The table below is missing from the preview, Am I doing something wrong?

![image](https://user-images.githubusercontent.com/65284010/104125149-67540680-536e-11eb-95da-f5927b416356.png)

**Comment by pradyunsg** [comment]
The headings are not properly aligned, which is making reST reject that as a table.

**Comment by pradyunsg** [comment]
Closing since there doesn't seem to be anything here to change in this extension. :)
