### ISSUE TITLE
Support nesting tabs

### ISSUE THREAD

**Issue by Jackenmen** [pradyunsg/sphinx-inline-tabs#9]
It is currently not possible to nest tabs:
![2021-02-27_16-21-09](https://user-images.githubusercontent.com/6032823/109391527-d504c380-7917-11eb-9941-b816059847b4.gif)

Source code for the GIF:
```rst
*****************
Operating systems
*****************

.. tab:: Windows

    Owned by Microsoft

.. tab:: Linux

    Created by Linus Torvalds

    .. tab:: Ubuntu

        Owned by Canonical

    .. tab:: CentOS

        Owned by Red Hat

.. tab:: MacOS

    Owned by Apple
```

**Comment by pradyunsg** [comment]
4b06cfeb5f9a21ed95d6d12d1a4eb3c4dea459f6 adds this. I'll cut a release later today.

**Comment by pradyunsg** [comment]
https://sphinx-inline-tabs.readthedocs.io/en/latest/usage.html#nesting for the docs. :)

**Comment by pradyunsg** [comment]
https://pypi.org/project/sphinx-inline-tabs/2021.4.11b8/ released!
